### PR TITLE
Use Generic Associated Types for Enum trait

### PR DESCRIPTION
**Pull request by sugar700**

### CODE REVIEW

**Comment by xfix** [comment]
The biggest issue is the length calculation:

```rust
#[doc(hidden)]
pub const fn enum_len<E: Enum>() -> usize {
    E::Array::<()>::LENGTH
}
```

Can we ensure that lengths match for all generic types?

**Comment by DCNick3** [comment]
Do you mean that for given `E` value `E::Array::<V>::LENGTH` should be the same for all `V`?

I don't think this can be enforced with rust type system, so probably make it a precondition of some unsafe trait?

**Comment by DCNick3** [comment]
As far as I understand:

- if no unsafe impl's for `Array` trait are present, the only types implementing them are the array types `[T; N]`
- The only way to refer to an array type generic over `T` is `[T; N]`
- `N` must be some constant expression
- You can't depend on generic parameter `T` in constant expression ([example](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=beb770d592657fd9668a56da628a94db)), so it's required to evaluate to the same constant no matter the `T`

As such, the array size can't change based on `T`.

Though, allowing the user to implement the `Array` trait complicates stuff... Is there any reason to allow it?

**Comment by xfix** [comment]
> Though, allowing the user to implement the `Array` trait complicates stuff... Is there any reason to allow it?

`Array` is sealed. `internal` is not a public module, and `Array` is intentionally not exported.

**Comment by DCNick3** [comment]
>Unless that doesn't work for effectively sealing traits?

It does. The usual way to seal a trait is to make it require another non-public one. Making the whole trait non-public should work too

>Even assuming it doesn't work, the trait is marked as unsafe, so implementations need to match its requirements.

Fair, it's just not clear to me what the requirements would be (because it's kinda dependent on `Enum` implementations too..). w/o user impls it's easier to reason about, so it probably should be kept this way.

**Comment by DCNick3** [comment]
With this PR being closed, are there any plans to bring the GATs in some other form?

**Comment by sugar700** [comment]
@DCNick3 Right, I forgot to archive the repo. GitHub recommends to close pull requests before archiving, and the project is now migrated to Codeberg where the pull request is still open: https://codeberg.org/xfix/enum-map.

**Pull request closed without merging**
